// CPU-only float32 investigation; preserves all captured native receipts.
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,join,dirname} from 'node:path';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {loadForest} from '../browser/forest-loader.mjs';
import {buildForestRasterData} from '../browser/forest-raster-worker.mjs';
import {sphereVisible,rotate,selectHierarchyLod} from '../browser/meshlet-hierarchy.mjs';
import {dotF32,transformPointF32,transformSphereF32,traceSphereF32,sphereVisibleF32,selectLodF32} from '../browser/forest-acceptance-f32.mjs';
import {triangleIntersects,predictFallbackCounts} from '../browser/forest-acceptance-plan.mjs';
const [assets,captureDir,outputPath]=process.argv.slice(2);if(!outputPath)throw Error('Usage: node tools/reproduce_float32_acceptance.mjs <forest assets> <capture directory> <output.json>');
const reports=[];for(let i=0;i<=26;i++)reports.push(JSON.parse(await readFile(join(resolve(captureDir),`grouped-acceptance-${String(i).padStart(3,'0')}.json`),'utf8')));
const target=reports[26],u=target.appliedUniforms,camera={eye:u.slice(0,3),right:u.slice(4,7),up:u.slice(8,11),forward:u.slice(12,15),tan:u[15],aspect:u[7],lodPixels:u[30]},sha=x=>createHash('sha256').update(x).digest('hex');
const originalFetch=globalThis.fetch;let forest;globalThis.fetch=async url=>{const name=new URL(url).pathname.slice(1);if(!['manifest.json','instrument.bin.gz','instances.bin.gz'].includes(name))throw Error('Unexpected asset');return new Response(await readFile(join(resolve(assets),name)));};
try{forest=await loadForest('https://cpu-forest.invalid/','forest');}finally{globalThis.fetch=originalFetch;}
const data=await buildForestRasterData(forest,{meshlets:true,limits:{drawGroupSize:8}}),plan=data.meshlets,values=new Float32Array(data.instances),words=new Uint32Array(data.instances),models=new Uint32Array(plan.models),errors=new Float32Array(plan.models),nodes=new Float32Array(plan.nodes),record=plan.records[2605],root=models[record.model*8+record.level],localSphere=Array.from(nodes.subarray(root*8,root*8+4));
const modelIds=new Uint16Array(data.count),fallbackDraws=new Int32Array(data.batches.length*4).fill(-1),fallbackSpheres=new Float32Array(data.batches.length*16);
for(let i=0;i<data.count;i++)modelIds[i]=words[i*12+8];
plan.records.forEach((r,draw)=>{if(!r.clustered){const key=r.model*4+r.level,n=models[r.model*8+r.level];fallbackDraws[key]=draw;fallbackSpheres.set(nodes.subarray(n*8,n*8+4),key*4);}});
const input={modelIds,instanceTransforms:values,fallbackDraws,fallbackSpheres,records:plan.records};
const candidates=[];let rootPopulation=0,rootPopulationF32=0,selectedPopulation64=0,selectedPopulationF32=0,selectedIndependentOfHistory=true;
for(let i=0;i<data.count;i++){const o=i*12;if(words[o+8]!==record.model)continue;const position=Array.from(values.subarray(o,o+3)),fullSphere=[...position,values[o+10]],root64=sphereVisible(fullSphere,camera),root32=sphereVisibleF32(fullSphere,camera);if(root64)rootPopulation++;if(root32)rootPopulationF32++;if(!root32&&!root64)continue;
 const e=errors.subarray(record.model*8+4,record.model*8+8),z=dotF32(position.map((x,k)=>Math.fround(x-camera.eye[k])),camera.forward);for(let prior=0;prior<4;prior++)if(selectLodF32(e,values[o+3],z,values[o+10],camera,prior)!==record.level)selectedIndependentOfHistory=false;
 const q=Array.from(values.subarray(o+4,o+8)),sphere64=[...rotate(q,localSphere.slice(0,3).map(x=>x*values[o+3])).map((x,k)=>x+position[k]),localSphere[3]*Math.abs(values[o+3])],sphere32=transformSphereF32(localSphere,values,o),v64=root64&&sphereVisible(sphere64,camera),trace32=traceSphereF32(sphere32,camera),v32=root32&&trace32.visible;
 if(v64)selectedPopulation64++;if(v32)selectedPopulationF32++;
 if(v64!==v32)candidates.push({id:i,model:record.model,modelId:data.batches[record.model].id,level:record.level,draw:2605,position,scale:values[o+3],rotation:q,fullRootRadius:values[o+10],localSphere,sphere64,sphere32,root64,root32,visible64:v64,visibleF32:v32,traceF32:trace32});
}
console.log(JSON.stringify({stage:'instance candidates',rootPopulation,rootPopulationF32,selectedPopulation64,selectedPopulationF32,selectedIndependentOfHistory,candidates}));
const capturedDifference=target.fallbackBoundsDifferences.find(x=>x.draw===2605);assert.equal(candidates.length,1);assert.equal(capturedDifference.actualCount,rootPopulation);assert.equal(capturedDifference.rootCount,rootPopulation);assert.equal(capturedDifference.selectedLodExpectedCount,selectedPopulation64);assert.equal(selectedPopulationF32,capturedDifference.actualCount);assert.equal(selectedIndependentOfHistory,true);
const state=new Uint32Array(data.count),history=new Uint32Array(data.count),stateChecks=[];
for(const captured of reports){if(captured.resetHistory)history.fill(0);const v=captured.appliedUniforms,c={eye:v.slice(0,3),right:v.slice(4,7),up:v.slice(8,11),forward:v.slice(12,15),tan:v[15],aspect:v[7],lodPixels:v[30]},populations=new Uint32Array(data.batches.length*4);let visible=0;
 for(let i=0;i<data.count;i++){const o=i*12,before=history[i],position=[values[o],values[o+1],values[o+2]],inside=sphereVisible([ ...position,values[o+10]],c);let after=before;if(inside){const m=words[o+8],z=position.reduce((n,x,k)=>n+(x-c.eye[k])*c.forward[k],0);after=selectHierarchyLod(errors.subarray(m*8+4,m*8+8),values[o+3],z,values[o+10],c,before);visible++;populations[m*4+after]++;}state[i]=before|(after<<2)|(inside?16:0);history[i]=after;}
 const digest=sha(new Uint8Array(state.buffer)),exact=digest===captured.lodStateSha256;assert.equal(exact,true,'Every reconstructed instance state word must match the native SHA before auditing counts');
 const predicted=predictFallbackCounts(state,input,c),differenceRows=new Map(captured.fallbackBoundsDifferences.map(x=>[x.draw,x]));let fallbackDrawsCompared=0;const fallbackFloat32Mismatches=[];
 // The runtime records every fallback row where normal != root population OR
 // normal != its old oracle. An absent row therefore has actual == population.
 plan.records.forEach((r,draw)=>{if(!r.clustered){const actual=differenceRows.get(draw)?.actualCount??populations[r.model*4+r.level];fallbackDrawsCompared++;if(actual!==predicted[draw])fallbackFloat32Mismatches.push({draw,actual,predicted:predicted[draw]});}});
 stateChecks.push({index:captured.index,stateSha256:digest,gpuStateSha256:captured.lodStateSha256,exact,visible,gpuVisible:captured.lod.visible,fallbackDrawsCompared,fallbackFloat32Mismatches});assert.equal(fallbackFloat32Mismatches.length,0);console.log(JSON.stringify({stage:'state/counts reconstructed',index:captured.index,exact,fallbackDrawsCompared,fallbackFloat32Mismatches}));
}
const dot=(a,b)=>a.reduce((n,x,k)=>n+x*b[k],0),tx=camera.tan*camera.aspect,planes=[p=>dot(p,camera.forward)-.05,p=>dot(p,camera.forward)*tx-dot(p,camera.right),p=>dot(p,camera.forward)*tx+dot(p,camera.right),p=>dot(p,camera.forward)*camera.tan-dot(p,camera.up),p=>dot(p,camera.forward)*camera.tan+dot(p,camera.up)];
for(const candidate of candidates){const lod=data.batches[record.model].levels[record.level],vertices=new Float32Array(lod.vertices),indices=new Uint32Array(lod.indices),unique=[...new Set(indices)],o=candidate.id*12;let clippedTriangles=0,clippedTrianglesF32=0,maximumVertexDistance=0,maximumVertexDistanceF32=0;const points=new Map(),pointsF32=new Map(),maxima=planes.map(()=>-Infinity),maximaF32=planes.map(()=>-Infinity);
 for(const index of unique){const local=Array.from(vertices.subarray(index*10,index*10+3)),p=rotate(candidate.rotation,local.map(x=>x*candidate.scale)).map((x,k)=>x+candidate.position[k]),p32=transformPointF32(local,values,o);points.set(index,p);pointsF32.set(index,p32);maximumVertexDistance=Math.max(maximumVertexDistance,Math.hypot(...p.map((x,k)=>x-candidate.sphere64[k])));maximumVertexDistanceF32=Math.max(maximumVertexDistanceF32,Math.hypot(...p32.map((x,k)=>x-candidate.sphere32[k])));planes.forEach((plane,k)=>{maxima[k]=Math.max(maxima[k],plane(p.map((x,j)=>x-camera.eye[j])));maximaF32[k]=Math.max(maximaF32[k],plane(p32.map((x,j)=>x-camera.eye[j])));});}
 for(let t=0;t<indices.length;t+=3){if(triangleIntersects(Array.from(indices.subarray(t,t+3),x=>points.get(x)),camera))clippedTriangles++;if(triangleIntersects(Array.from(indices.subarray(t,t+3),x=>pointsF32.get(x)),camera))clippedTrianglesF32++;}
 const d=candidate.sphere64.slice(0,3).map((x,k)=>x-camera.eye[k]),z=dot(d,camera.forward),x=dot(d,camera.right),r=candidate.sphere64[3]+Math.max(1,...candidate.sphere64.slice(0,3).map(Math.abs),...camera.eye.map(Math.abs))*2e-6,horizontal=z*tx+r*Math.sqrt(1+tx*tx);
 candidate.traceFloat64={d,z,x,tx,inflatedRadius:r,horizontal,horizontalMargin:horizontal-Math.abs(x)};candidate.triangles=indices.length/3;candidate.clippedTriangles=clippedTriangles;candidate.clippedTrianglesF32=clippedTrianglesF32;candidate.maximumVertexDistance=maximumVertexDistance;candidate.maximumVertexDistanceF32=maximumVertexDistanceF32;candidate.planeMaximumSignedDistances=maxima;candidate.planeMaximumSignedDistancesF32=maximaF32;candidate.reconstructedState=state[candidate.id];candidate.classification='conservative GPU false positive: extra wholly off-frustum geometry; no omitted instance';
 assert.equal(clippedTriangles,0);assert.equal(clippedTrianglesF32,0);assert.ok(maxima.some(x=>x<0)&&maximaF32.some(x=>x<0));assert.ok(maximumVertexDistance<=candidate.sphere64[3]&&maximumVertexDistanceF32<=candidate.sphere32[3]);
}
const result={status:'CPU investigation; native count receipt remains failed',gpuUsed:false,browserUsed:false,capturedPairSha256:sha(await readFile(join(resolve(captureDir),'grouped-acceptance-026.json'))),rootPopulation,rootPopulationF32,selectedPopulation64,selectedPopulationF32,selectedIndependentOfHistory,capturedDifference,instanceIdentification:'GPU count equals exact root/model/LOD population, and an unclustered fallback emits once per eligible instance; all root-visible model-457 LOD-3 instances were retained. Instance 368645 is the sole float64-rejected member.',countEvidence:'Every fallback row where normal differs from root population or from the v2 CPU oracle was recorded; absent rows therefore equal the SHA-verified root/model/LOD population. Full native visible-list buffers were not separately saved.',stateChecks,candidates,source:data.provenance};
await mkdir(dirname(resolve(outputPath)),{recursive:true});await writeFile(resolve(outputPath),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({stage:'complete',output:resolve(outputPath),allStateWordsExact:stateChecks.every(x=>x.exact),candidates:candidates.length}));
